# Sign up user
POST http://localhost:7003/user/signup
Content-Type: application/json

{
    "name":"collinsfrontenddev",
    "email":"collinsfrontenddev@gmail.com",
    "password":"Password@1"
}

# Login user
###
POST http://localhost:7003/user/login
Content-Type: application/json

{
    "email":"collinsfrontend@gmail.com",
    "password":"Password@1"
}


###
GET  http://localhost:7003/user/homepage
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjJiNDY3M2I2LTRhN2YtNGMyOC1hYzA0LTMyODdhMjhiY2M3ZCIsIm5hbWUiOiJ1c2VyMiIsImVtYWlsIjoidXNlcjJAZ21haWwuY29tIiwicm9sZSI6ImN1c3RvbWVyIiwid2VsY29tZSI6IjAiLCJpYXQiOjE2NjMyNDcyNjEsImV4cCI6MTY2MzI1MDg2MX0.0iBIcI8bRlXtNupwavCjYTIZSrV3EF_FQ_jw-JP_iNE



###
GET  http://localhost:7003/user/check
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjJiNDY3M2I2LTRhN2YtNGMyOC1hYzA0LTMyODdhMjhiY2M3ZCIsIm5hbWUiOiJ1c2VyMiIsImVtYWlsIjoidXNlcjJAZ21haWwuY29tIiwicm9sZSI6ImN1c3RvbWVyIiwid2VsY29tZSI6IjAiLCJpYXQiOjE2NjMyNDcyNjEsImV4cCI6MTY2MzI1MDg2MX0.0iBIcI8bRlXtNupwavCjYTIZSrV3EF_FQ_jw-JP_iNE


# Fetch all users
###
GET  http://localhost:7003/user/users


# Add parcels
###
POST http://localhost:7003/parcel/add
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQyOTQyNjk1LTc4ZmYtNDg2Ny1hNjYyLTNlYWNlNjEyMzkxMiIsIm5hbWUiOiJjb2xsaW5zIiwiZW1haWwiOiJjb2xsaW5zZnJvbnRlbmRAZ21haWwuY29tIiwicm9sZSI6ImN1c3RvbWVyIiwid2VsY29tZSI6IjEiLCJpYXQiOjE2NjM5MTkxOTcsImV4cCI6MTY2MzkyMjc5N30.OudiE99upaYe2W2qCTIAJBR4hj-T0UZw9j32cqFxGOk


{
    "senderName": "new",
    "receiverName":"johh",
   "senderEmail":"user1@gmail.com",
    "receiverEmail":"jonathanndambuki16@gmail.com",
    "origin":"nyeri",
    "destination":"nairobi",
    "dispatchedDate":"2022-09-30",
    "deliveryDate":"2022-09-29",
    "weight":100,
    "price":1000,
    "receiverLat": 786677,
    "receiverLng": 788899,
    "senderLat": 99999,
    "senderLng": 97777
}


# View all parcels
###
GET  http://localhost:7003/parcel/all
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmMGQ1OThjLWIzMDktNDkzOC1iNjBjLWQ5OTJmMGE4NzEzMCIsIm5hbWUiOiJjb2xsaW5zIiwiZW1haWwiOiJjb2xsaW5zZnJvbnRlbmRAZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwid2VsY29tZSI6IjAiLCJpYXQiOjE2NjM5MDI3NDksImV4cCI6MTY2MzkwNjM0OX0.-Nh0ylyVcCZHWVpGhQDTUA8V7fusJR00BsisnPWtAgE



# Update parcel
###
PUT http://localhost:7003/parcel/update/8c420cab-7c2d-4766-a15f-91437c57cc10
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmMGQ1OThjLWIzMDktNDkzOC1iNjBjLWQ5OTJmMGE4NzEzMCIsIm5hbWUiOiJjb2xsaW5zIiwiZW1haWwiOiJjb2xsaW5zZnJvbnRlbmRAZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwid2VsY29tZSI6IjAiLCJpYXQiOjE2NjM5MDI3NDksImV4cCI6MTY2MzkwNjM0OX0.-Nh0ylyVcCZHWVpGhQDTUA8V7fusJR00BsisnPWtAgE


{
    "senderName": "new eeddupdated mercy",
    "receiverName":"doe",
    "senderEmail":"lxwaihenya@gmail.com",
    "receiverEmail":"doe@gmail.com",
    "origin":"nyeri",
    "destination":"nairobi",
    "dispatchedDate":"today",
    "deliveryDate":"tomorrow",
    "weight":100,
    "price":1000,
    "receiverLat": 786677,
    "receiverLng": 788899,
    "senderLat": 99999,
    "senderLng": 97777
}


# Soft delete
###
DELETE   http://localhost:7003/parcel/delete/8c420cab-7c2d-4766-a15f-91437c57cc10
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmMGQ1OThjLWIzMDktNDkzOC1iNjBjLWQ5OTJmMGE4NzEzMCIsIm5hbWUiOiJjb2xsaW5zIiwiZW1haWwiOiJjb2xsaW5zZnJvbnRlbmRAZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwid2VsY29tZSI6IjAiLCJpYXQiOjE2NjM5MDI3NDksImV4cCI6MTY2MzkwNjM0OX0.-Nh0ylyVcCZHWVpGhQDTUA8V7fusJR00BsisnPWtAgE


# View one parcel
###
GET  http://localhost:7003/parcel/view/5bd98561-d3af-4f57-8537-133a31c1f387
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmMGQ1OThjLWIzMDktNDkzOC1iNjBjLWQ5OTJmMGE4NzEzMCIsIm5hbWUiOiJjb2xsaW5zIiwiZW1haWwiOiJjb2xsaW5zZnJvbnRlbmRAZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwid2VsY29tZSI6IjAiLCJpYXQiOjE2NjM5MDI3NDksImV4cCI6MTY2MzkwNjM0OX0.-Nh0ylyVcCZHWVpGhQDTUA8V7fusJR00BsisnPWtAgE


# deliver a parcel
###
Get http://localhost:7003/parcel/delivered/8c420cab-7c2d-4766-a15f-91437c57cc10
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQyOTQyNjk1LTc4ZmYtNDg2Ny1hNjYyLTNlYWNlNjEyMzkxMiIsIm5hbWUiOiJjb2xsaW5zIiwiZW1haWwiOiJjb2xsaW5zZnJvbnRlbmRAZ21haWwuY29tIiwicm9sZSI6ImN1c3RvbWVyIiwid2VsY29tZSI6IjEiLCJpYXQiOjE2NjM5MTkxOTcsImV4cCI6MTY2MzkyMjc5N30.OudiE99upaYe2W2qCTIAJBR4hj-T0UZw9j32cqFxGOk


# send by user
###
GET http://localhost:7003/user/sent/user2@gmail.com


# received by user
###
GET http://localhost:7003/user/received/user1@gmail.com


