
POST http://localhost:7003/user/signup
Content-Type: application/json

{
    "name":"user5",
    "email":"user5@gmail.com",
    "password":"Password@1"
}



###
POST http://localhost:7000/user/login
Content-Type: application/json

{
    "email":"user2@gmail.com",
    "password":"12345678"
}


###

GET  http://localhost:7000/user/homepage
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjkwMmFmNDc0LWVkMjgtNGYwMy1hMTdkLWNhOTE4YzY4NWY0NSIsIm5hbWUiOiJ1c2VyMiIsImVtYWlsIjoidXNlcjJAZ21haWwuY29tIiwicm9sZSI6InVzZXIiLCJzdGF0dXMiOiIwIiwiaWF0IjoxNjYxOTE1NjczLCJleHAiOjE2NjE5MTkyNzN9.OOeFKRapCOhoUDIDTvflLeJx5nHlbHihow52jAdn_M8


###

GET  http://localhost:7000/user/check
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjkwMmFmNDc0LWVkMjgtNGYwMy1hMTdkLWNhOTE4YzY4NWY0NSIsIm5hbWUiOiJ1c2VyMiIsImVtYWlsIjoidXNlcjJAZ21haWwuY29tIiwicm9sZSI6InVzZXIiLCJzdGF0dXMiOiIwIiwiaWF0IjoxNjYxOTE1NjczLCJleHAiOjE2NjE5MTkyNzN9.OOeFKRapCOhoUDIDTvflLeJx5nHlbHihow52jAdn_M8



###
GET  http://localhost:7003/user/users


# parcels
###
POST http://localhost:7003/parcel/addparcel
Content-Type: application/json

{
    "senderName": "joe",
    "receiverName":"mary",
    "senderEmail":"joe@gmail.com",
    "receiverEmail":"mary@gmail.com",
    "origin":"nyeri",
    "destination":"nairobi",
    "dispatchedDate":"today",
    "deliveryDate":"tomorrow",
    "weight":100,
    "price":1000
}

###
POST http://localhost:7000/project/assignNewProject
Content-Type: application/json

{   "name":"project 1",
    "user_id":"ffba3ac2-e3aa-47af-9575-79db177b2e80"}

###
DELETE  http://localhost:7003/parcel/parcels/66b23eb6-fe07-4b4d-ac15-5f6d5d0183e0


###
GET  http://localhost:7003/parcel/parcels

###
GET  http://localhost:7003/parcel/parcels/04a600c5-d632-4bd4-922a-bc7ccfbe77db

###
Get http://localhost:7000/project/complete/54cac16d-c214-4c22-8121-77d451800310

###

PUT http://localhost:7003/parcel/parcels/update/04a600c5-d632-4bd4-922a-bc7ccfbe77db
Content-Type: application/json

{
    "senderName": "jack",
    "receiverName":"doe",
    "senderEmail":"jack@gmail.com",
    "receiverEmail":"doe@gmail.com",
    "origin":"nyeri",
    "destination":"nairobi",
    "dispatchedDate":"today",
    "deliveryDate":"tomorrow",
    "weight":100,
    "price":1000
}