
POST http://localhost:7002/user/signup
Content-Type: application/json

{
    "name":"user2",
    "email":"user2@gmail.com",
    "password":"Password@1"
}

###
POST http://localhost:7002/user/login
Content-Type: application/json

{
    "email":"user2@gmail.com",
    "password":"Password@1"
}


###
GET  http://localhost:7003/user/homepage
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjJiNDY3M2I2LTRhN2YtNGMyOC1hYzA0LTMyODdhMjhiY2M3ZCIsIm5hbWUiOiJ1c2VyMiIsImVtYWlsIjoidXNlcjJAZ21haWwuY29tIiwicm9sZSI6ImN1c3RvbWVyIiwid2VsY29tZSI6IjAiLCJpYXQiOjE2NjMyNDcyNjEsImV4cCI6MTY2MzI1MDg2MX0.0iBIcI8bRlXtNupwavCjYTIZSrV3EF_FQ_jw-JP_iNE


###
GET  http://localhost:7003/user/check
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjJiNDY3M2I2LTRhN2YtNGMyOC1hYzA0LTMyODdhMjhiY2M3ZCIsIm5hbWUiOiJ1c2VyMiIsImVtYWlsIjoidXNlcjJAZ21haWwuY29tIiwicm9sZSI6ImN1c3RvbWVyIiwid2VsY29tZSI6IjAiLCJpYXQiOjE2NjMyNDcyNjEsImV4cCI6MTY2MzI1MDg2MX0.0iBIcI8bRlXtNupwavCjYTIZSrV3EF_FQ_jw-JP_iNE


###
GET  http://localhost:7002/user/users


# parcels
###
POST http://localhost:7002/parcel/add
Content-Type: application/json

{
    "senderName": "mary",
    "receiverName":"johh",
   "senderEmail":"user1@gmail.com",
    "receiverEmail":"user2@gmail.com",
    "origin":"nyeri",
    "destination":"nairobi",
    "dispatchedDate":"2022-09-30",
    "deliveryDate":"2022-09-29",
    "weight":100,
    "price":1000,
    "receiverLat": 786677,
  "receiverLng": 788899,
  "senderLat": 99999,
  "senderLng": 97777
}

###
GET  http://localhost:7002/parcel/all

###
PUT http://localhost:7002/parcel/update/6583326d-16ed-4cc5-84ed-ee09cb77f93f
Content-Type: application/json

{
    "senderName": "updated mercy",
    "receiverName":"doe",
    "senderEmail":"lxwaihenya@gmail.com",
    "receiverEmail":"doe@gmail.com",
    "origin":"nyeri",
    "destination":"nairobi",
    "dispatchedDate":"today",
    "deliveryDate":"tomorrow",
    "weight":100,
    "price":1000
}

###
DELETE   http://localhost:7002/parcel/delete/fcc94233-6ead-45a9-99e9-54cd8eb5ea16


###
GET  http://localhost:7002/parcel/view/995a4109-3ef7-4561-9a68-3bbae685eb0b

###
Get http://localhost:7002/parcel/delivered/db49d89f-0ca0-4c44-9773-10352befb919

###
GET http://localhost:7002/user/sent/jack@gmail.com
###
GET http://localhost:7002/user/received/user@gmail.com


